name: Merge PR from Fork

on:
  pull_request:
    types: [submitted]

jobs:
  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"

    - name: Merge PR
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
        REPO_OWNER=$(echo "${{ github.repository_owner }}")
        REPO_NAME=$(echo "${{ github.event.repository.name }}")

        echo "Merging PR #$PR_NUMBER in $REPO_OWNER/$REPO_NAME"

        curl -X PUT \
          -H "Authorization: token $PAT_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/merge \
          -d '{"commit_title": "Merging PR #'"$PR_NUMBER"'", "merge_method": "merge"}'
