name: Merge Approved PRs

on:
  pull_request_review:
    types: 
      - submitted  # Triggers when a review is submitted

permissions:
  pull-requests: write  # Ensure the action has permission to merge PRs

jobs:
  auto-merge-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Auto-merge PR if approved
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Checking if the PR has been approved"
        
        # Extract necessary PR information
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        REPO_OWNER=$(jq -r '.repository.owner.login' "$GITHUB_EVENT_PATH")
        REPO_NAME=$(jq -r '.repository.name' "$GITHUB_EVENT_PATH")

        echo "PR Number: $PR_NUMBER"
        echo "Repository: $REPO_OWNER/$REPO_NAME"

        # Check if the PR is approved
        APPROVALS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/reviews" | 
            jq '[.[] | select(.state == "APPROVED")] | length')

        echo "Number of approvals: $APPROVALS"

        if [ "$APPROVALS" -ge 1 ]; then
          echo "PR is approved. Attempting to merge."
          curl -s -X PUT -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/merge" \
            -d '{"commit_title": "Auto-merged by GitHub Actions", "merge_method": "merge"}'
        else
          echo "PR is not yet approved. No action taken."
        fi
