name: Merge PR from Fork

on:
  pull_request_review:  # Run only when a review is submitted
    types: [submitted]   # Run when a review is submitted (not just opened)
    
jobs:
  merge_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Grant write access to merge PRs
      contents: write       # Grant access to repo contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Set up GitHub CLI
      run: |
        echo "Installing GitHub CLI"
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Check PR Approval Status
      id: check_approval
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Checking review status for PR #$PR_NUMBER"
        
        # Get the reviews for the PR and check if it is approved
        REVIEWS=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/reviews --jq '.[] | select(.state == "APPROVED")')
        
        if [ -z "$REVIEWS" ]; then
          echo "No approvals found. Skipping merge."
          exit 1  # Stop the workflow if there are no approved reviews
        else
          echo "PR has been approved. Proceeding with the merge."
        fi

    - name: Merge PR
      if: success()  # Ensure previous step succeeded (PR is approved)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "Merging pull request #$PR_NUMBER"
        
        # Merge the PR using GitHub CLI
        gh pr merge $PR_NUMBER --repo ${{ github.repository }} --merge --admin
