name: Merge PR from Fork

on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Check if the PR is approved
      id: check_approval
      run: |
        PR_REVIEW_STATE=$(jq --raw-output .pull_request.reviewers[0].state < $GITHUB_EVENT_PATH)
        if [[ "$PR_REVIEW_STATE" != "APPROVED" ]]; then
          echo "PR is not approved, exiting"
          exit 1
        fi

    - name: Merge PR
      if: steps.check_approval.outcome == 'success'
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number < $GITHUB_EVENT_PATH)
        curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"merge_method":"merge"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge"
