name: Auto-merge PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git for merging
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if PR is approved
        id: check_approval
        run: |
          APPROVED=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | \
            jq '[.[] | select(.state == "APPROVED")] | length')
          echo "PR approved count: $APPROVED"
          if [ "$APPROVED" -eq 0 ]; then
            echo "PR is not approved yet"
            exit 1
          fi

      - name: Merge the PR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          git fetch origin
          git checkout main
          git pull origin main
          git merge --no-ff "refs/pull/$PR_NUMBER/merge" -m "Auto-merge PR #$PR_NUMBER"
          git push origin main
