name: Auto-merge PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Set up Git for merging
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Fetch the PR source branch dynamically and merge it
      - name: Fetch and merge PR branch
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_BRANCH="${{ github.head_ref }}"  # Dynamically get the source branch from the PR

          # Fetch the source branch (PR branch)
          git fetch origin $PR_BRANCH

          # Switch to the target branch (main)
          git checkout main

          # Pull the latest changes from the main branch
          git pull origin main

          # Merge the source branch (PR branch) into main
          git merge --no-ff "origin/$PR_BRANCH" -m "Auto-merge PR #$PR_NUMBER"

          # Push the merged changes to the main branch
          git push origin main
